


spring:
  mail:
    host: smtp.gmail.com
    username: firozabbas.edunext@gmail.com
    password: fewilsdpexeoavlo
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

